### ISSUE TITLE
Authentication into AEP from Kafka Connect Causes crash

### ISSUE THREAD

**Issue by del57361** [adobe/experience-platform-streaming-connect#8] opened 2020-12-02 21:35 UTC
### Subject of the issue
Describe your issue here.

### Your environment
* version of docker
[AuthAEP_Kafak_Connector_Log_docker.txt](https://github.com/adobe/experience-platform-streaming-connect/files/5632135/AuthAEP_Kafak_Connector_Log_docker.txt)

### Steps to reproduce
`docker exec -i experience-platform-streaming-connect_kafka-connect_1 ./setup.sh`

Entered the Below according to AEP Project Config - we are able to send Postman GET/POST Requests to AEP 

Tried with Default and custom settings 
```
Enter IMS ORG
<IMS-ORG>
Enter Client ID
***
Enter Client Secret
***
Enter JWT Token
***
```

### Expected Behavior
```
Enter Schema Name: [default: Streaming_Connect_Schema_20191014074347]

Making call to create schema to https://platform.adobe.io/ with name Streaming_Connect_Schema_20191014074347
Schema ID: https://ns.adobe.com/<tenant>/schemas/<schema ID>
Enter Dataset Name: [default: Streaming_Ingest_Test_20191014074347]

Making call to create dataset to https://platform.adobe.io/ with name Streaming_Ingest_Test_20191014074347
Data Set: ["@/dataSets/<Dataset ID>"]
Enter Streaming Connection Name: [default: My Streaming Connection-20191014074347]

Enter Streaming Connection Source: [default: My Streaming Source-20191014074347]

Making call to create streaming connection to https://platform.adobe.io/ with name My Streaming Connection-20191014074347 and source My Streaming Source-20191014074347
Streaming Connection: https://dcs.adobedc.net/collection/<Streaming Connection ID>
AEP Sink Connector aep-sink-connector-20191014074347
Enter the number of Experience events to publish
100
Publishing 100 messages for Data set <Dataset ID> and schema https://ns.adobe.com/<tenant>/schemas/<schema ID>
Published 100 messages
```

**Comment by nipunnair** [comment] 2021-04-29 03:58
Resolving this. The root cause of this was a misconfiguration that was addressed.

**Closed by nipunnair** 2021-04-29 03:58 UTC
